name: angel
description: A graphql starter application for Angel3 framework
publish_to: none 
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  angel3_auth: ^8.0.0
  angel3_configuration: ^8.0.0
  angel3_framework: ^8.0.0
  angel3_graphql: ^8.0.0
  angel3_jael: ^8.0.0
  angel3_production: ^8.0.0
  angel3_container: ^8.0.0
  angel3_static: ^8.0.0
  angel3_validate: ^8.0.0
  angel3_serialize: ^8.0.0
  graphql_server2: ^6.0.0
  graphql_schema2: ^6.0.0
  file: ^7.0.0
  logging: ^1.2.0
dev_dependencies:
  angel3_hot: ^8.0.0
  angel3_serialize_generator: ^8.0.0
  angel3_test: ^8.0.0
  graphql_generator2: ^6.0.0
  belatuk_pretty_logging: ^6.0.0
  build_runner: ^2.0.4 
  io: ^1.0.0 
  test: ^1.21.0
  lints: ^2.1.1