name: angel
version: 1.0.0
description: A basic starter application template for Angel3 framework
publish_to: none
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  angel3_auth: ^6.0.0
  angel3_configuration: ^6.0.0
  angel3_framework: ^6.0.0
  angel3_jael: ^6.0.0
  angel3_production: ^6.0.0
  angel3_static: ^6.0.0
  angel3_validate: ^6.0.0
  belatuk_pretty_logging: ^4.0.0
dev_dependencies:
  angel3_hot: ^6.0.0
  angel3_test: ^6.0.0
  io: ^1.0.0
  test: ^1.21.0
  lints: ^1.0.0




