name: angel
version: 1.0.0
description: A basic starter application template for Angel3 framework
publish_to: none
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  angel3_auth: ^7.0.0
  angel3_configuration: ^7.0.0
  angel3_framework: ^7.0.0
  angel3_jael: ^7.0.0
  angel3_production: ^7.0.0
  angel3_static: ^7.0.0
  angel3_validate: ^7.0.0
  belatuk_pretty_logging: ^5.0.0
dev_dependencies:
  angel3_hot: ^7.0.0
  angel3_test: ^7.0.0
  io: ^1.0.0
  test: ^1.21.0
  lints: ^2.0.0




