name: angel
version: 1.0.0
description: An ORM starter application for Angel3 framework
publish_to: none
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  angel3_auth: ^6.0.0
  angel3_configuration: ^6.0.0
  angel3_framework: ^6.0.0
  angel3_jael: ^6.0.0
  angel3_migration: ^6.0.0
  angel3_orm: ^6.0.0
  angel3_orm_mysql: ^6.0.0-beta.1
  angel3_serialize: ^6.0.0
  angel3_production: ^6.0.0
  angel3_static: ^6.0.0
  angel3_validate: ^6.0.0
  belatuk_pretty_logging: ^4.0.0
  optional: ^6.0.0
  logging: ^1.0.0
dev_dependencies:
  angel3_hot: ^6.0.0
  angel3_migration_runner: ^6.0.0
  angel3_orm_generator: ^6.0.0
  angel3_serialize_generator: ^6.0.0
  angel3_test: ^6.0.0
  build_runner: ^2.0.3
  io: ^1.0.0
  test: ^1.21.0
  lints: ^1.0.0
