name: angel
version: 1.0.0
description: An ORM starter application for Angel3 framework
publish_to: none
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  angel3_auth: ^7.0.0
  angel3_configuration: ^7.0.0
  angel3_framework: ^7.0.0
  angel3_jael: ^7.0.0
  angel3_migration: ^7.0.0
  angel3_orm: ^7.0.0
  angel3_orm_mysql: ^7.0.0-beta.1
  angel3_serialize: ^7.0.0
  angel3_production: ^7.0.0
  angel3_static: ^7.0.0
  angel3_validate: ^7.0.0
  belatuk_pretty_logging: ^5.0.0
  optional: ^6.0.0
  logging: ^1.0.0
dev_dependencies:
  angel3_hot: ^7.0.0
  angel3_migration_runner: ^7.0.0
  angel3_orm_generator: ^7.0.0
  angel3_serialize_generator: ^7.0.0
  angel3_test: ^7.0.0
  build_runner: ^2.0.3
  io: ^1.0.0
  test: ^1.21.0
  lints: ^2.0.0
